### ISSUE TITLE
Analytics related bundles are missing when we start API-M 3.0 with different profiles in distributed deployment

### ISSUE THREAD

**Issue by akurathimohan** [wso2/analytics-apim#1045] opened 2020-03-09 14:06 UTC
**Description:**
I'm trying to implement distributed deployment with API-M 3.0, Identity Server-5.9.0 and Analytics 3.0 

**Issue:**
api#am#admin#v0.15 web application is missing in both Publisher and Store (\repository\deployment\server\webapps) after starting the API-M with Publisher and Store profiles. Due to this API's count, Applications count and Subscriptions count always showing as zero in Analytics dashboard.

**Steps to reproduce**
Create an optimized distributions for all components 

-Dprofile=gateway-worker   
-Dprofile=traffic-manager
-Dprofile=api-publisher
-Dprofile=api-devportal

I'm using Identity Server-5.9.0 as Key Manager

Start the components in same order

worker.bat --run (Analytics Worker)
wso2server.bat -run (Key Manager)
wso2server.bat -Dprofile=traffic-manager
wso2server.bat -Dprofile=api-publisher
wso2server.bat -Dprofile=api-devportal
wso2server.bat -Dprofile=gateway-worker
dashboard.bat --run (Analytics Dashboard)

**Comment by fazlan-nazeem** [comment] 2020-03-12 10:05
@akurathimohan we have fixed this with the upcoming 3.1 release and furthermore the issue is fixed via WUM updates for 3.0 as well. If you have a subscription, please update the distribution and retest this.

**Closed by fazlan-nazeem** 2020-03-12 10:05 UTC

**Comment by fazlan-nazeem** [comment] 2020-03-12 10:13
related git issue https://github.com/wso2/product-apim/issues/6686
