### ISSUE TITLE
Error in terminal when deploying the purging business rule

### ISSUE THREAD

**Issue by Mariangela** [wso2/analytics-apim#588] opened 2018-09-27 04:45 UTC
**Description:**
The following error occurs when the default business rule related to alert data purging is deployed. Please see **Steps to reproduce:** for more details. Please note that even though the desired functionality works, which is purging data with regard to alert tables, the error in the terminal will trigger questions among the users, because if everything is working correctly an error message should not have got triggered. Therefore, please look at this error from that angle and rectify it. 

`[2018-09-27 09:39:58,849] ERROR {org.wso2.msf4j.internal.MSF4JWSConnectorListener} - Method invocation failed: java.lang.reflect.InvocationTargetException`

**Suggested Labels:**
Bug

**Suggested Assignees:**
@chamilaadhi 

**Affected Product Version:**
APIM 2.6.0 RC3

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
1. Start the Analytics server, APIM server, and the Dashboard node.
2. Access the Business rules.
3. Edit the APIM DATA PURGING business rule by changing the "Time Interval For Trigger" to 1 seconds.
4. Click **Save and deploy**.
The following messages appeared in the terminal:

- Dashboard node:
```
[2018-09-27 09:39:58,849] ERROR {org.wso2.msf4j.internal.MSF4JWSConnectorListener} - Method invocation failed: java.lang.reflect.InvocationTargetException
[2018-09-27 09:40:57,717]  INFO {org.wso2.carbon.business.rules.core.services.TemplateManagerService} - Business rule APIM DATA PURGING updated in the database.
```
- Analytics node
```
[2018-09-27 09:38:04,397]  INFO {org.wso2.extension.siddhi.io.mgwfile.task.MGWFileCleanUpTask} - Uploaded API Usage data in the db will be cleaned up to : 2018-09-22 09:38:04.394
[2018-09-27 09:40:57,832]  INFO {org.wso2.carbon.stream.processor.core.internal.util.SiddhiAppFilesystemInvoker} - Siddhi App: apim_analytics_data_purging_app_0 saved in the filesystem
[2018-09-27 09:41:00,732]  INFO {org.wso2.carbon.stream.processor.core.internal.StreamProcessorService} - Siddhi App apim_analytics_data_purging_app_0 deployed successfully
[2018-09-27 10:08:04,481]  INFO {org.wso2.extension.siddhi.io.mgwfile.task.MGWFileCleanUpTask} - Uploaded API Usage data in the db will be cleaned up to : 2018-09-22 10:08:04.478
```

**Related Issues:**
N/A

**Comment by ruks** [comment] 2020-07-14 06:27
Cannot reproduce in 3.2.0 Analytics snapshot. Hence closing. 

Dashboard
```
[2020-07-14 11:54:05,549]  INFO {org.wso2.carbon.business.rules.core.services.TemplateManagerService} - Business rule APIM DATA PURGING updated in the database.
```

Worker
```
[2020-07-14 11:54:05,756]  INFO {org.wso2.carbon.streaming.integrator.core.internal.util.SiddhiAppFilesystemInvoker} - Siddhi App: apim_analytics_data_purging_app_0 saved in the filesystem
[2020-07-14 11:54:06,133]  INFO {org.wso2.carbon.streaming.integrator.core.internal.StreamProcessorService} - Siddhi App apim_analytics_data_purging_app_0 deployed successfully
```

**Closed by ruks** 2020-07-14 06:27 UTC
Labels: APIM 2.6.0, Type/Bug
