### ISSUE TITLE
CustomTable.jsx and CustomTableHead.jsx files have duplicate code in widgets which have tables

### ISSUE THREAD

**Issue by TanyaM** [wso2/analytics-apim#1116] opened 2020-04-28 10:49 UTC
**Description:**
Widgets that have tables consist of two files that contain table related logic implementations and these two files in each widgets mostly have duplicated code. We need to move the common logic into common libs and reuse it in other widgets.

22 widgets have this CustomTable.jsx file and CustomTableHeader.jsx file.

Few are listed below.

[1] https://github.com/wso2/analytics-apim/blob/master/components/org.wso2.analytics.apim.widgets/APIMApiUsage/src/CustomTable.jsx
[2] https://github.com/wso2/analytics-apim/blob/master/components/org.wso2.analytics.apim.widgets/APIMApiUsage/src/CustomTableHead.jsx

[3] https://github.com/wso2/analytics-apim/blob/master/components/org.wso2.analytics.apim.widgets/APIMApiRatings/src/CustomTable.jsx
[4] https://github.com/wso2/analytics-apim/blob/master/components/org.wso2.analytics.apim.widgets/APIMApiRatings/src/CustomTableHead.jsx

22 widgets have this CustomTable.jsx file and CustomTableHeader.jsx file.

**Comment by pahans** [comment] 2020-07-10 19:21
duplicate of https://github.com/wso2/analytics-apim/issues/896

**Closed by pahans** 2020-07-10 19:21 UTC
Labels: APIM-3.1.0-GA
