### ISSUE TITLE
wso2 3.0.0 analytics issue while loggin in dashboard

### ISSUE THREAD

**Issue by kalevivek11** [wso2/analytics-apim#907] opened 2020-01-15 04:42 UTC
I am following link
https://apim.docs.wso2.com/en/latest/Learn/Analytics/configuring-apim-analytics/#quick-setup

database: Mysql

steps to reproduce:

keep analytics and apim(ALL-IN-ONE) in same directory
change the database connections
start worker profile
start apim
start dashboard

username: admin
password : admin

{"error":"Internal_Server_Error","description":"Error occurred \u0027analytics-dashboard\u0027. Error : \u0027Connection refused: connect executing POST https://localhost/oauth2/token\u0027"}

![analyticsDashboard](https://user-images.githubusercontent.com/10954248/72405599-7f0aa600-377f-11ea-9151-b98892441fe6.JPG)

**Comment by RAVEENSR** [comment] 2020-01-18 16:19
This issue is a duplicate of https://github.com/wso2/analytics-apim/issues/906

**Closed** 2020-02-10 12:01 UTC
