### ISSUE TITLE
API Availability chart legend goes out of the border

### ISSUE THREAD

**Issue by fazlan-nazeem** [wso2/analytics-apim#1003] opened 2020-02-25 04:38 UTC
**Description:**
Please see following image.

<img width="771" alt="Screenshot 2020-02-25 at 10 06 44 AM" src="https://user-images.githubusercontent.com/13759167/75215435-b759c700-57b6-11ea-948c-7cd508b67981.png">

**Comment by pahans** [comment] 2020-02-25 04:49
Related to https://github.com/wso2/analytics-apim/issues/986

**Comment by pahans** [comment] 2020-02-25 05:07
duplicate of https://github.com/wso2/analytics-apim/issues/739

**Closed by pahans** 2020-02-25 05:07 UTC
Labels: APIM 3.1.0
