### ISSUE TITLE
Loading of aggregation data into in-memory aggregation runtimes cause out of memory issue

### ISSUE THREAD

**Issue by menakaj** [wso2/analytics-apim#608] opened 2019-05-10 12:07 UTC
**Description:**

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
2.6.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by ruks** [comment] 2020-07-10 08:17
Cannot reproduce and upgraded to the latest siddhi dependencies in Analytics 3.2.0.
Hence closing.

**Closed by ruks** 2020-07-10 08:17 UTC
