### ISSUE TITLE
Dropdown content only partially accessible in analytics dashboard permission settings.

### ISSUE THREAD

**Issue by Ketharan** [wso2/analytics-apim#1098] opened 2020-03-27 08:37 UTC
**Description:**
See the below diagram. Happens for the scope selection for viewer permission level.

![scroll_issue](https://user-images.githubusercontent.com/25489203/77737188-795cf680-7033-11ea-86d0-36c7d0ee01f2.png)

The drop-down is not scroll-able, and part of the list loads outside the screen. Requires to resize the browser in order to access the full list.

**Suggested Labels:**
Type/Improvement

**Affected Product Version:**
3.1.0-RC-4

**OS, DB, other environment details and versions:**    
Firefox (74.0), Ubuntu

**Comment by ruks** [comment] 2020-04-20 05:37
But I think it supports search by typing in the input field. But +1 for the scroll bar.

**Comment by RAVEENSR** [comment] 2020-04-21 07:48
This is an issue in material-ui(https://github.com/mui-org/material-ui/issues/7738). In this case, we are using AutoComplete module in material-ui(v0.20.0) to populate the scopes. To fix this issue, we need to bump the material ui version to 1.0.0. But the problem is there are so many breaking changes from v0.20.0 to v1.0.0. So that upgrading to material-ui v1.0.0 takes a considerable amount of work and time as we need to test out whole dashboard with the latest change. Since this already gives results when typing, for now I think we can ignore this issue.

**Comment by Ketharan** [comment] 2020-04-30 10:46
For this case, what about adding a scrollbar to the page instead of that dropdown. Since the number of items in the list is around 5 or 6, adding a scrollbar to the page will not be a problem I think.

**Comment by RAVEENSR** [comment] 2020-04-30 12:08
AFAIK that auto complete is generated according to the space in the window. Providing a drop down will not solve the issue IMO. However we may try and see.

**Comment by Ketharan** [comment] 2020-05-04 04:51
As @RAVEENSR said, the autocomplete is generated according to the space in the window. I tried adding a scrollbar but the issue is not resolved. Once a scope is added we can have some space in the bottom and the autocomplete list will eventually grow. Therefore as @RAVEENSR suggested we can ignore and close this issue.

**Comment by ruks** [comment] 2020-07-10 06:27
Closing the ticket as per the above discussion.

**Closed by ruks** 2020-07-10 06:27 UTC
